### ISSUE TITLE
Dataset link not working

### ISSUE THREAD

**Issue by vijay-jaisankar** [Gariscat/HouseX#1]
Hello,

Thanks for open-sourcing your paper and code, the results look very interesting! 

Unfortunately, the [Google Drive](https://drive.google.com/drive/u/0/folders/1Vmo9jMYbo0p1agjDoga7Onj1i4WbI4Wk) link containing the dataset gives a 404 error and is hence not accessible.
Also, is there any scope of releasing your pre-trained models for drop/climax detection?

Thanks!
Vijay (vijay.jaisankar@iiitb.ac.in)

**Comment by Gariscat** [comment]
Hi, Vijay!

Sorry for this confusion.
The raw audio data is here:
https://drive.google.com/drive/folders/1xd_fHDz-oDjW51CIzcaM8CInlzUeJCnL?usp=sharing
.
And the mel-spectrograms are here:
https://drive.google.com/file/d/1Rc_ATUY9-0spcC6662V_5e6Xl9okM3hn/view?usp=sharing
.

The drop is manually labelled for this work. I remember other works
available in recent years (perhaps I have cited them in the HouseX paper?)
on drop detection. You can take a look if you are interested :)

On Tue, Jan 2, 2024 at 3:30 PM Vijay Jaisankar ***@***.***>
wrote:

> Hello,
>
> Thanks for open-sourcing your paper and code, the results look very
> interesting!
>
> Unfortunately, the Google Drive
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__drive.google.com_drive_u_0_folders_1Vmo9jMYbo0p1agjDoga7Onj1i4WbI4Wk&d=DwMCaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=2V93HzaTdKPxIttDVdQ0hg&m=kLxBZdQG8yBNQNGkjywOOQ5wWXaCclTza42u36NANXJLAQbSBHq-f25GUVhR8X7E&s=1g4FIEDfLKild1yaAdPUgNT88M-ilvRPRlngAY5C8aY&e=>
> link containing the dataset gives a 404 error and is hence not accessible.
> Also, is there any scope of releasing your pre-trained models for
> drop/climax detection?
>
> Thanks!
> Vijay ***@***.***)
>
> —
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_Gariscat_HouseX_issues_1&d=DwMCaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=2V93HzaTdKPxIttDVdQ0hg&m=kLxBZdQG8yBNQNGkjywOOQ5wWXaCclTza42u36NANXJLAQbSBHq-f25GUVhR8X7E&s=n-52STjj29RKSe8_oTeIWsOkMwG56PTY58gc38n7pd8&e=>,
> or unsubscribe
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_ARHTLEXBJZPDIACAAOIMUDTYMPVWVAVCNFSM6AAAAABBJ5CGVOVHI2DSMVQWIX3LMV43ASLTON2WKOZSGA3DEMRYHE4DOOA&d=DwMCaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=2V93HzaTdKPxIttDVdQ0hg&m=kLxBZdQG8yBNQNGkjywOOQ5wWXaCclTza42u36NANXJLAQbSBHq-f25GUVhR8X7E&s=EtfeeT078n9dZUYMcJ-WSxbwi02n6pSq8t3R4eKQfa0&e=>
> .
> You are receiving this because you are subscribed to this thread.Message
> ID: ***@***.***>
>


-- 
Regards,
Xinyu Li

**Comment by vijay-jaisankar** [comment]
Hello! Thank you so much for your reply - the dataset is accessible now :)
Sure, will check out the papers you cited in the HouseX paper!

Thanks!
~Vijay
